### ISSUE TITLE
feature request: clear the histogram

### ISSUE THREAD

**Issue by imandr** [diana-hep/histbook#13]
Could you please add a method to clear histogram counts ?
How about a histogram book ?
Thanks.

**Comment by jpivarski** [comment]
Now there's `clear` (changes `Hist` and `Book` in place) and `cleared` (returns a cleared copy). I also took the opportunity to add scalar multiplication, which is like a generalization of clearing (though maybe the multiply by zero case should defer to `clear`?).

Would it be okay if I accumulated these feature requests in the [enhancements branch](https://github.com/diana-hep/histbook/tree/enhancements) and only push to master and bump the version number for PyPI when there's a lot of them? Is it easy for you to check out that branch with git and `python setup.py install --user` instead of `pip install histbook --user`?

Feel free to make a lot of requests as you encounter missing features.
